# Stripped down .zshrc additions when setting up a new machine

ZSH_THEME="lambda-mod"

export ZSH="/Users/jonnyp/.oh-my-zsh"

plugins=(
  nvm
  autojump
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# autoload node when using nvm and cd into a directory with a .nvmrc file
zstyle ':omz:plugins:nvm' silent-autoload yes # optionally remove the output generated by NVM when autoloading